; --- ESP32-C6 (CDC + RGB LED) ---
; --- Standard coordinator Now -> MQTT ---
[env:coordinator_c6]
board = esp32-c6-devkitc-1
board_build.flash_mode = dio
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D HAS_RGB_LED
    -D UM_DEBUG_MODE=1
monitor_dtr = 1    ; <-- ADD THIS: Tells the C6 a terminal is connected
monitor_rts = 1    ; <-- ADD THIS
build_src_filter = 
    -<*> 
    +<coordinators/coordinator.cpp>
lib_deps = 
    ${common_libs.lib_deps_common}
    adafruit/Adafruit NeoPixel @ ^1.12.3
lib_ignore = 
    ${common_libs.lib_deps_ignore}
