; --- SENSOR NODE EXAMPLE (Generic) ---
[env:sensor_node]
board = esp32dev 
build_src_filter = -<*> +<nodes/sensor_node.example.cpp>

; --- ESP32-C6 SENSOR NODE ---
[env:sensor_node_c6]
board = esp32-c6-devkitc-1
board_build.flash_mode = dio
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D UM_DEBUG_MODE=1
monitor_dtr = 1
monitor_rts = 1
build_src_filter = 
    -<*> 
    +<sensors/sensor_node.cpp>  ; <-- Force it to compile the example file
lib_deps = 
    ${common_libs.lib_deps_sensor_node}
lib_ignore = 
    ${common_libs.lib_deps_ignore}
